version: '3'

services:
  cineam:
    image: cineam
    container_name: cineam
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - redis
    networks:
      - zelo

  

networks:
  zelo:
    driver: bridge