version: '3'

redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - .db:/data
    restart: on-failure:5
    networks:
      - zelo

services:
  web:
    image: cineam
    build:
      context: .
      dockerfile: Dockerfile
    environment:
       REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3005:3005
    depends_on:
      - redis
    networks:
      - zelo

  

networks:
  zelo:
    driver: bridge